In [1]:
pip install numpy

Requirement already satisfied: numpy in /srv/conda/envs/notebook/lib/python3.7/site-packages (1.21.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install pandas

Requirement already satisfied: pandas in /srv/conda/envs/notebook/lib/python3.7/site-packages (1.3.5)
Requirement already satisfied: numpy>=1.17.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas) (2022.1)
Requirement already satisfied: six>=1.5 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install matplotlib

Requirement already satisfied: matplotlib in /srv/conda/envs/notebook/lib/python3.7/site-packages (3.5.2)
Requirement already satisfied: packaging>=20.0 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib) (21.3)
Requirement already satisfied: fonttools>=4.22.0 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib) (4.33.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib) (1.4.3)
Requirement already satisfied: pillow>=6.2.0 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib) (9.1.1)
Requirement already satisfied: cycler>=0.10 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib) (3.0.7)
Requirement already satisfied: numpy>=1.17 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: typing-extensions in /srv/conda/envs/notebook/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib) (4.1.1)
Requirement already satisfied: six>=1.5 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip install sklearn

Requirement already satisfied: sklearn in /srv/conda/envs/notebook/lib/python3.7/site-packages (0.0)
Requirement already satisfied: scikit-learn in /srv/conda/envs/notebook/lib/python3.7/site-packages (from sklearn) (1.0.2)
Requirement already satisfied: joblib>=0.11 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from scikit-learn->sklearn) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from scikit-learn->sklearn) (3.1.0)
Requirement already satisfied: numpy>=1.14.6 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from scikit-learn->sklearn) (1.21.6)
Requirement already satisfied: scipy>=1.1.0 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from scikit-learn->sklearn) (1.7.3)
Note: you may need to restart the kernel to use updated packages.

In [5]:
#These libraries are reqyured to manage the servicedesk dataset
# Numpy: used for large, multi-dimensional arrays and matrices, and for high-level mathematical functions
# Pandas: used for data manipulation and analysis
# matplotlib: used for visualisation and plotting graph/image/etc
# sklearn for splitting training data
# sklearn for linear regression model
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.linear_model as skl_lm
from sklearn.model_selection import train_test_split

In [6]:
# Import the service desk dataset
# head visualise the first five rows of the dataset
servicedesk = pd.read_csv('Dataset3.csv')
servicedesk.head()

,State,Priority,Assigned Group,Severity,P1 Incident,Urgency,Made SLA,Reassignment count
0,Closed,4,1,3,0,4,1,1
1,Closed,3,1,3,0,3,1,2
2,Closed,3,2,3,0,3,1,1
3,Closed,3,2,3,0,3,1,4
4,Closed,3,2,3,0,3,1,1

In [7]:
#explore continious feature
servicedesk.describe()

,Priority,Assigned Group,Severity,P1 Incident,Urgency,Made SLA,Reassignment count
count,4518.000000,4518.000000,4518.0,4518.000000,4518.000000,4518.000000,4518.000000
mean,3.027003,2.066180,3.0,0.014830,3.026782,0.948207,2.180832
std,0.362238,0.663614,0.0,0.120884,0.362560,0.221633,1.779602
min,1.000000,1.000000,3.0,0.000000,1.000000,0.000000,0.000000
25%,3.000000,2.000000,3.0,0.000000,3.000000,1.000000,1.000000
50%,3.000000,2.000000,3.0,0.000000,3.000000,1.000000,2.000000
75%,3.000000,3.000000,3.0,0.000000,3.000000,1.000000,3.000000
max,4.000000,3.000000,3.0,1.000000,4.000000,1.000000,17.000000

In [8]:
servicedesk.groupby('Made SLA').mean()

,Priority,Assigned Group,Severity,P1 Incident,Urgency,Reassignment count
Made SLA,,,,,,
0,2.948718,2.064103,3.0,0.047009,2.948718,2.132479
1,3.031279,2.066293,3.0,0.013072,3.031046,2.183473

In [9]:
servicedesk.groupby('P1 Incident').mean()

,Priority,Assigned Group,Severity,Urgency,Made SLA,Reassignment count
P1 Incident,,,,,,
0,3.052348,2.066277,3.0,3.052123,0.949899,2.178836
1,1.343284,2.059701,3.0,1.343284,0.835821,2.313433

In [10]:
servicedesk.groupby('Urgency').mean()

,Priority,Assigned Group,Severity,P1 Incident,Made SLA,Reassignment count
Urgency,,,,,,
1,1.000000,2.000000,3.0,1.000000,0.826923,2.211538
2,2.012195,2.036585,3.0,0.085366,0.817073,2.463415
3,3.000000,2.092225,3.0,0.001962,0.953642,2.063527
4,4.000000,1.739414,3.0,0.000000,0.931596,3.657980

In [11]:
servicedesk.groupby('Priority').mean()

,Assigned Group,Severity,P1 Incident,Urgency,Made SLA,Reassignment count
Priority,,,,,,
1,2.000000,3.0,1.000000,1.000000,0.826923,2.211538
2,2.037037,3.0,0.086420,2.000000,0.814815,2.481481
3,2.092202,3.0,0.001962,2.999755,0.953654,2.063266
4,1.739414,3.0,0.000000,4.000000,0.931596,3.657980

In [12]:
servicedesk.groupby('Severity').mean()

,Priority,Assigned Group,P1 Incident,Urgency,Made SLA,Reassignment count
Severity,,,,,,
3,3.027003,2.06618,0.01483,3.026782,0.948207,2.180832

In [13]:
#drop all excess and continious features
cont_feat=['State', 'Severity', 'Assigned Group', 'Made SLA' , 'Priority' , 'Reassignment count']
servicedesk.drop(cont_feat, axis=1, inplace=True)
servicedesk.head()

   P1 Incident  Urgency
0            0        4
1            0        3
2            0        3
3            0        3
4            0        3

In [14]:
servicedesk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4518 entries, 0 to 4517
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   P1 Incident  4518 non-null   int64
 1   Urgency      4518 non-null   int64
dtypes: int64(2)
memory usage: 70.7 KB

In [15]:
features = servicedesk.drop('P1 Incident', axis=1)
labels = servicedesk['P1 Incident']

#Stage one split 60% to training set and 40% to training set
x_train, x_test, y_train, y_test = train_test_split(features, labels, test_size=0.4, random_state=42)
# Stage 2 split training set into 20% validation and 20% Test
x_test, x_val, y_test, y_val = train_test_split(x_test, y_test, test_size=0.5, random_state=42)

In [16]:
print(len(labels), len(y_train), len(y_val), len(y_test))

4518 2710 904 904

In [22]:
# import regression from sklearn
from sklearn.linear_model import LinearRegression

In [24]:
# reshape the X so it is a 2D array, which sklearn model usually expect
X = servicedesk['data'][:,0:3] # 'Urgency'
y = servicedesk['data'][:,3] # 'P1 Incident'
X.shape

KeyError: 'data'